apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build-pod
spec:
  containers:
  - name: git-clone
    image: alpine/git:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      git clone https://github.com/ksrinimba/kaniko.git /workspace  && ls -lR /workspace
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=dir:///workspace/"
    - "--context-sub-path=/image-content/helloweb/"
    - "--dockerfile=Dockerfile"
    - "--destination=ksrinimba/hello-web:1.3"
      #- "--dockerfile=Dockerfile"
      #- "--cache=true"
      #- "--cache-ttl=24h"
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace
    - name: kaniko-secret
      mountPath: /kaniko/.docker
        #   securityContext:
        #runAsUser: 1000
        #runAsGroup: 1000
  restartPolicy: Never
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: kaniko-secret
    secret:
      secretName: srinidocker
      items:
        - key: .dockerconfigjson
          path: config.json        
