---
# Source: hello-web/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-hello-web
  labels:
    helm.sh/chart: hello-web-1.0.0
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
